version: "3"

volumes:
  mysql-volume:

services:
  # PHPコンテナ
  app:
    # contaier_name: php
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src/:/var/www/html
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=${DB_NAME}
      - DB_USERNAME=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}

  # Webコンテナ(Nginx)
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - ${WEB_PORT}:80
    depends_on:
      - app
    volumes:
      - ./src/:/var/www/html

  # Mysqlコンテナ
  db:
    #M1macだとこれが必要
    platform: linux/x86_64
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      TZ: "Asia/Tokyo"
    volumes:
      - mysql-volume:/var/lib/mysql
