version: '3'

services:
  workspace:
    container_name: php_workspace
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - app_net

  db:
    container_name: mysql
    image: mysql:5.7
    platform: linux/x86_64 #M1macだとこれが必要
    restart: unless-stopped
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
      MYSQL_USER: test
      MYSQL_PASSWORD: test
    networks:
      - app_net

volumes:
  mysql-data:

networks:
  app_net:
    driver: bridge
